/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:37a6a898-53c6-4be8-8add-97886e460339",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_Am5YUzR1u",
    "aws_user_pools_web_client_id": "3580hpp9g63oa9g1ock2km5vf7",
    "oauth": {},
    "aws_dynamodb_all_tables_region": "us-east-1",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "amplifyworkshopitems-master",
            "region": "us-east-1"
        }
    ],
    "aws_cloud_logic_custom": [
        {
            "name": "amplifyworkshopapi",
            "endpoint": "https://19y3i2cmz6.execute-api.us-east-1.amazonaws.com/master",
            "region": "us-east-1"
        }
    ],
    "aws_mobile_analytics_app_id": "21c854f12cbc4971b6cccc846ead09e0",
    "aws_mobile_analytics_app_region": "us-east-1",
    "aws_content_delivery_bucket": "amplifyecommerce-20200726100336-hostingbucket-master",
    "aws_content_delivery_bucket_region": "us-east-1",
    "aws_content_delivery_url": "http://amplifyecommerce-20200726100336-hostingbucket-master.s3-website-us-east-1.amazonaws.com"
};


export default awsmobile;
